layout: sidebar
style: dark

profile_pic: https://scontent-atl3-1.cdninstagram.com/v/t51.2885-19/s320x320/47447651_2043689225923450_1978481452316098560_n.jpg?_nc_ht=scontent-atl3-1.cdninstagram.com&_nc_ohc=gIZK6kPl0h0AX8QizwD&oh=a63e539c42201b9cdaf69bae6c5da2f6&oe=5F3A6FBF
page_title: sketches i've made
repo_name: p5_portfolio
desc: Click a sketch to see it in action. If you're on mobile, I'd recommend viewing these on my Instagram.

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: spannbaueradam
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: ASpannbauer
  # unsplash: your_username
  # vk: your_username
  website: https://adamspannbauer.github.io/
  # youtube: your_username

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
